### ISSUE TITLE
Could the scratch pad auto-save?

### ISSUE THREAD

**Issue by GreenAsJade** [destradax/scratch#8]
... so even if you elect to close it by a binding that close the pane, or the top right close bytton, it doesn't have to ask you if you want to save ... because it's always saved.

**Comment by destradax** [comment]
Sure thing! Thanks for the suggestion.

**Comment by destradax** [comment]
Hello @GreenAsJade!
I just added support for autosave in [Release 1.2.0](https://github.com/destradax/scratch/releases/tag/v1.2.0), although for now it only works with the toggle command (Ctrl+Alt+,).
Still need to add support for autosave if you close the scratch file from the close button.
I'll keep working on it.

**Comment by GreenAsJade** [comment]
Sweet - that fully solves it as far as I'm concerned.   I'll just use c-a-,  :)   Smooth-as :D
